services:
  dev-db:
    image: postgres:14
    ports: 
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lab-postgres
      POSTGRES_DB: nest
      POSTGRES_PASSWORD: "123"
  test-db:
    image: postgres:14
    ports: 
      - 5435:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lab-postgres
      POSTGRES_DB: nest
      POSTGRES_PASSWORD: "123"
volumes:
  db-data:
